#For Reference Only
services:
  postgres_db:
    image: postgres:17-alpine
    container_name: jual_postgres_db
    restart: always
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1G
    environment:
      POSTGRES_USER: ${DB_USER:-admin}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME:-jual_db}
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        ["CMD-SHELL", "pg_isready -U ${DB_USER:-admin} -d ${DB_NAME:-jual_db}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - default

  backend:
    image: ghcr.io/gutiere5/jual-backend:latest
    container_name: jual-backend
    restart: always
    environment:
      DATABASE_URL: "postgresql://${DB_USER}:${DB_PASSWORD}@postgres_db:5432/${DB_NAME}?schema=public"
      PORT: 3000
      JWT_SECRET: ${JWT_SECRET}
      CORS_ORIGIN: ${CORS_ORIGIN_URLS}
      JWT_EXPIRES_IN: 1
      NODE_ENV: production
    ports:
      - "3000:3000"
    depends_on:
      postgres_db:
        condition: service_healthy
    networks:
      - default
      - proxy_shared

  jual-dashboard:
    image: ghcr.io/gutiere5/jual-dashboard:latest
    container_name: jual-dashboard
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - backend
    networks:
      - default
      - proxy_shared

  jual-editor:
    image: ghcr.io/gutiere5/jual-editor:latest
    container_name: jual-editor
    restart: always
    ports:
      - "3002:3002"
    depends_on:
      - backend
    networks:
      - default
      - proxy_shared

  jual-display:
    image: ghcr.io/gutiere5/jual-display:latest
    container_name: jual-display
    restart: always
    ports:
      - "3003:3003"
    depends_on:
      - backend
    networks:
      - default
      - proxy_shared

volumes:
  postgres_data:

networks:
  proxy_shared:
    external: true
