services:
  postgres_db:
    image: postgres:17-alpine
    container_name: jual_postgres_db
    restart: always
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1G
    environment:
      POSTGRES_USER: ${DB_USER:-admin}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME:-jual_db}
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        ["CMD-SHELL", "pg_isready -U ${DB_USER:-admin} -d ${DB_NAME:-jual_db}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - default

volumes:
  postgres_data:

networks:
  proxy_shared:
    external: true
